// <auto-generated />
namespace YummyProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class image_file_prop : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(image_file_prop));
        
        string IMigrationMetadata.Id
        {
            get { return "202501010935241_image_file_prop"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
